FROM php:8.1-apache


RUN a2enmod rewrite


RUN apt-get update && apt-get install -y \
    libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


COPY ./src/ /var/www/html/

EXPOSE 80