FROM php:8.2-cli

RUN apt-get update && apt-get install -y \
    libzip-dev \
    unzip \
    libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql \
    && pecl install redis \
    && docker-php-ext-enable redis

WORKDIR /app

COPY . .

EXPOSE 3000

CMD ["php", "-S", "0.0.0.0:3000", "index.php"]
